#!/bin/sh

cd /var/www/home-management

git pull origin master

npm install

npm run build

source venv/bin/activate

flask db stamp head

flask db migrate

flask db upgrade

deactivate

sudo service apache2 restart

sudo sytemctl reload apache2