#!/bin/sh

cd /var/www/home-management

git pull origin master

npm install

npm run build

source venv/bin/activate

pip install -r requirements.txt

flask db stamp head

flask db migrate

flask db upgrade

deactivate

sudo service apache2 restart

sudo systemctl reload apache2