"""empty message

Revision ID: 4e3a8f28586a
Revises: d44c511abb5c
Create Date: 2024-08-08 10:44:10.492823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3a8f28586a'
down_revision = 'd44c511abb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('things_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=225), nullable=False),
    sa.Column('filename', sa.String(length=225), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
